#! /bin/bash

cd /home/shubhamiit/workload


echo hi

workload=`cat workload`

if [[ $workload == "rr" ]];then
	
	curr=`cat curr`

	curr=$((curr+1))
	echo "$curr" > curr
	cp rr.f."$curr" rr.f.active
	echo "'" |  sudo -S bash /home/shubhamiit/workload/rr.f.active 2>>errors
fi


 
if [[ $workload == "ws" ]];then

	curr=`cat curr`
	
	curr=$((curr+1))
	echo "$curr" > curr
	cp ws.f."$curr" ws.f.active

fi
	
if [[ $workload == "fs" ]];then
	
	curr=`cat curr`
	
	curr=$((curr+1))
	echo "$curr" > curr
	cp fs.f."$curr" fs.f.active
	
	
fi
