#! /bin/bash


cd /home/shubhamiit/workload
workload=`cat workload`

if [[ $workload == "make" ]];then

    cd /home/shubhamiit/linux
    make clean
    make
fi


if [[ $workload == "rr" ]];then

date
echo "'" | sudo -S sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
./writefile file1 .35 r 1024 600 10007

date 

fi

if [[ $workload == "ws" ]];then

date

echo 0 | sudo tee /proc/sys/kernel/randomize_va_space
echo "'" | sudo -S sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
echo "'" | sudo -S rm -rf /mnt/*
date >> errors
head ws.f.active
echo "'" | sudo -S filebench -f /home/shubhamiit/workload/ws.f.active 2>> errors
date


fi

if [[ $workload == "fs" ]];then
date
echo "'" | sudo -S rm -rf /mnt/*
echo 0 | sudo tee /proc/sys/kernel/randomize_va_space
echo "'" | sudo -S sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
date >> errors
head fs.f.active
echo "'" | sudo -S filebench -f /home/shubhamiit/workload/fs.f.active 2>> errors
date
fi



